name: book_report_app
description: 독후감 프로젝트.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  jiffy: ^5.0.0
  cached_network_image: ^3.1.0

flutter:
  uses-material-design: true
