name: book_report_app
description: 독후감 프로젝트.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.5
  faker: ^2.0.0
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  jiffy: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/svgs/
